POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "username": "Tom",
    "password": "december"
}

###
GET http://localhost:4000/api/v1/restaurants
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiVG9tIiwiZW1haWwiOiJ0b21AZ21haWwuY29tIiwicGFzc3dvcmQiOiJkZWNlbWJlciJ9LCJpYXQiOjE2MDEyNDAxNjR9.YshlcjnUgrPaMqDVP40RZ5lZ68qu68e99je666Wgy10

###
POST http://localhost:4000/api/v1/restaurants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiVG9tIiwiZW1haWwiOiJ0b21AZ21haWwuY29tIiwicGFzc3dvcmQiOiJkZWNlbWJlciJ9LCJpYXQiOjE2MDEyNDAxNjR9.YshlcjnUgrPaMqDVP40RZ5lZ68qu68e99je666Wgy10

{
  "name": "brand new restaurant",
  "description": "very tasty food"
}

###
GET http://localhost:4000/api/v1/restaurants/5f7328feea87634bd4d610b5
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiVG9tIiwiZW1haWwiOiJ0b21AZ21haWwuY29tIiwicGFzc3dvcmQiOiJkZWNlbWJlciJ9LCJpYXQiOjE2MDEyNDAxNjR9.YshlcjnUgrPaMqDVP40RZ5lZ68qu68e99je666Wgy10


###
DELETE http://localhost:4000/api/v1/restaurants/5f7328feea87634bd4d610b5
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiVG9tIiwiZW1haWwiOiJ0b21AZ21haWwuY29tIiwicGFzc3dvcmQiOiJkZWNlbWJlciJ9LCJpYXQiOjE2MDEyNDAxNjR9.YshlcjnUgrPaMqDVP40RZ5lZ68qu68e99je666Wgy10

###

PATCH http://localhost:4000/api/v1/restaurants/5f73214b15147a6a88036540
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiVG9tIiwiZW1haWwiOiJ0b21AZ21haWwuY29tIiwicGFzc3dvcmQiOiJkZWNlbWJlciJ9LCJpYXQiOjE2MDEyNDAxNjR9.YshlcjnUgrPaMqDVP40RZ5lZ68qu68e99je666Wgy10

{
  "name": "favourite restaurant"
}